name: test github action 
on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  test_job_1:
    name: building ${{ matrix.spec.name }}
    runs-on: ${{ windows-latest }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Run test script with bool param
        run: powershell -Command ".\test-bool.ps1 -Flag \$true"
