name: test github action 
on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  test_job_1:
    strategy:
      fail-fast: false
      matrix:
        spec:
          - { name: 'linux x86_64', runner: ubuntu-latest }
          - { name: 'macOS x86_64', runner: macos-latest }
          - { name: 'Windows x86_64', runner: windows-latest }
    name: building ${{ matrix.spec.name }}
    runs-on: ${{ matrix.spec.runner }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Python Tools
        run: python -m pip install -U pip setuptools

      - name: Install Ziti
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: python run-tests.py

      - name: Find Ziti
        id: findziti
        shell: bash
        run: |
          ZITI=$(find "$HOME" -type f \( -name ziti -o -name ziti.exe \) -perm /u+x | head -n1)
          echo "ziti_path=$ZITI" >> "$GITHUB_OUTPUT"

      - name: Run Ziti
        shell: bash
        run: |
          "${{ steps.findziti.outputs.ziti_path }}" --version