name: Dial via ZET

on:
  workflow_dispatch:

jobs:
  dial-ziti-service:
    runs-on: ubuntu-latest
    env:
      ZITI_IDENTITY_JSON: ${{ secrets.ZITI_IDENTITY_JSON }}
      ZITI_SERVICE: "your.service.name"
    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update && \
          sudo apt-get install -y unzip curl jq

      - name: Download Ziti Edge Tunnel
        run: |
          curl -sL https://github.com/openziti/ziti-tunnel-sdk-c/releases/latest/download/ziti-edge-tunnel-Linux_x86_64.zip \
            -o zet.zip && \
          unzip zet.zip && chmod +x ziti-edge-tunnel

      - name: Write identity file
        run: |
          echo "$ZITI_IDENTITY_JSON" > id.json

      - name: Run ZET and dial
        run: |
          sudo ./ziti-edge-tunnel run -i id.json &
          sleep 5
          timeout 10s curl -sk https://mgmt.ziti:8441 || true
